version: '3.7'

services:

  traduora:
    image: everco/ever-traduora:latest
    container_name: traduora
    build:
      context: .
      dockerfile: Dockerfile
      args:
          NODE_ENV: ${NODE_ENV:-production}
    ports:
     - "8000:8080"
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      TR_SIGNUPS_ENABLED: <TR_SIGNUPS_ENABLED>
      TR_AUTH_GOOGLE_ENABLED: <TR_AUTH_GOOGLE_ENABLED>
      TR_AUTH_GOOGLE_CLIENT_SECRET: '<TR_AUTH_GOOGLE_CLIENT_SECRET>'
      TR_AUTH_GOOGLE_CLIENT_ID: '<TR_AUTH_GOOGLE_CLIENT_ID>'
      TR_AUTH_GOOGLE_REDIRECT_URL: '<TR_AUTH_GOOGLE_REDIRECT_URL>'
      TR_MAIL_SENDER: '<TR_MAIL_SENDER>'
      TR_MAIL_HOST: '<TR_MAIL_HOST>'
      TR_MAIL_USER: '<TR_MAIL_USER>'
      TR_MAIL_PASSWORD: '<TR_MAIL_PASSWORD>'
      TR_DB_HOST: '<DB_HOST>'
      TR_DB_PORT: '<DB_PORT>'
      TR_DB_USER: '<DB_USER>'
      TR_DB_PASSWORD: '<DB_PASSWORD>'
      TR_DB_DATABASE: '<DB_NAME>' 
      TR_VIRTUAL_HOST: <FULL_DOMAIN>
    entrypoint: './docker-entrypoint.compose.sh'
    restart: on-failure
